# Generated by Django 5.0.2 on 2025-03-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
