# Generated by Django 5.0.2 on 2025-05-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_sentemail_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='mailgun_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='open_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
