# Generated by Django 5.0.2 on 2025-05-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('emails', '0003_sentemail_click_count_sentemail_mailgun_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='campaign',
            name='from_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='emails.emailtemplate'),
        ),
    ]
